services:
  backend:
    build: ./soliBackend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=soliBackend.settings
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - TABLE_NAME=users
      - BUCKET_NAME=storage
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=lambda,dynamodb,s3,elasticache
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN-}
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
